---
variables:
  TF_MIN_VERSION: "{{cookiecutter.tofu_min_version}}"
  AZURERM_PROVIDER_MIN_VERSION: "{{cookiecutter.azurerm_min_version}}"

include:
  - project: "claranet/projects/cloud/azure/terraform/ci"
    ref: master
    file: "/pipeline.yml"
